name: hsseq
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  provider: ^6.0.4
  http: ^0.13.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  fluttertoast: ^8.1.1
  path: ^1.8.2
  path_provider: ^2.0.11
  cached_network_image: ^3.2.2
  flutter_cache_manager: ^3.3.0
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  photo_view: ^0.14.0
  #file_picker: ^5.2.2
  sqflite: ^2.2.0+3
  shimmer: ^2.0.0
  ionicons: ^0.2.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
